# Generated by Django 5.2.7 on 2025-11-13 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Veillez entrez un numéro valide (8 chiffres)', regex='^(2[0-9]{7}|3[0-9]{7}|4[0-9]{7}|6[0-9]{7}|7[0-9]{7})$')])),
            ],
        ),
    ]
